### ISSUE TITLE
yaml multiline string formatting is lost upon using `npm`

### ISSUE THREAD

**Issue by airtonix** [reggi/package-yml#3]
```yml
scripts:
  dev: |-
    echo "Something"
    echo "Something Else"
  dev:foo: |-
    echo "Yet more things"
    npm run dev
  dev:bar: >-
    echo "Yet more things"
    npm run dev
```

ends up being turned into: 
```yml
scripts:
  dev: |-
    echo "Something"
    echo "Something Else"
  'dev:foo': |-
    echo "Yet more things";
    npm run dev
  'dev:bar': echo "Yet more things"; npm run dev
```

I posit that package-yml should either just ignore the `scripts` section or look in a key `config.package-yml` for some rules about desired behaviour.

```yml
scripts:
   ...
"package-yml":
  transform:
    out:
      - "*"
    in:
      - "!scripts"
```
